name: Build Android Kernel

on:
  workflow_dispatch:

jobs:
  set-repos:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.set-repos.outputs.repos }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set repos
        id: set-repos
        run: |
          echo "repos=$(jq -c . ${{ github.workspace }}/repos.json)" >> $GITHUB_OUTPUT

  build-kernel:
    needs: set-repos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.set-repos.outputs.repos) }}
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo.url }}
          ref: ${{ matrix.repo.branch }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang make gcc git bc bison flex libssl-dev libncurses5-dev libelf-dev

      - name: Configure kernel
        run: |
          make O=out ARCH=arm64 ${{ matrix.repo.config }}

      - name: Build kernel
        run: |
          make O=out ARCH=arm64 -j$(nproc)

      - name: Upload kernel image
        uses: actions/upload-artifact@v3
        with:
          name: kernel-image
          path: out/arch/arm64/boot/Image.gz-dtb
