name: Build External Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential bc bison flex libssl-dev \
            libncurses5-dev libelf-dev git curl wget

      # 🔽 Clone kernel din GitHub (NU din repo-ul tău)
      - name: Clone kernel source
        run: |
          git clone --depth=1 --branch rawr-bpf \
          https://github.com/LumiPlayground/android_kernel_samsung_sm8150 kernel

      # 🔽 Toolchains
      - name: Clone GCC
        run: |
          git clone --depth=1 https://github.com/mvaisakh/gcc-arm64 kernel/toolchain/gcc-cfp/gcc-cfp-single

      - name: Clone Clang
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang kernel/toolchain/llvm-arm-toolchain-ship

      - name: Clone DTC
        run: |
          git clone --depth=1 https://github.com/qcom-opensource/dtc kernel/tools/dtc

      # 🔽 Build kernel
      - name: Build kernel
        run: |
          cd kernel

          export ARCH=arm64
          mkdir -p out

          BUILD_CROSS_COMPILE=$(pwd)/toolchain/gcc-cfp/gcc-cfp-single/bin/aarch64-linux-gnu-
          KERNEL_LLVM_BIN=$(pwd)/toolchain/llvm-arm-toolchain-ship/bin/clang
          CLANG_TRIPLE=aarch64-linux-gnu-
          KERNEL_MAKE_ENV="DTC_EXT=$(pwd)/tools/dtc CONFIG_BUILD_ARM64_DT_OVERLAY=y"

          make -j$(nproc) O=out $KERNEL_MAKE_ENV ARCH=arm64 CROSS_COMPILE=$BUILD_CROSS_COMPILE REAL_CC=$KERNEL_LLVM_BIN CLANG_TRIPLE=$CLANG_TRIPLE r5q_eur_open_defconfig

          make -j$(nproc) O=out $KERNEL_MAKE_ENV ARCH=arm64 CROSS_COMPILE=$BUILD_CROSS_COMPILE REAL_CC=$KERNEL_LLVM_BIN CLANG_TRIPLE=$CLANG_TRIPLE

      # 🔽 Upload rezultat
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: kernel/out/arch/arm64/boot/Image
